package templates

var NET = `
TYPE=Ethernet
PROXY_METHOD=none
BROWSER_ONLY=no
BOOTPROTO=none
DEFROUTE=yes
IPV4_FAILURE_FATAL=no
IPV6INIT=yes
IPV6_AUTOCONF=yes
IPV6_DEFROUTE=yes
IPV6_FAILURE_FATAL=no
NAME=eth0
DEVICE=eth0
ONBOOT=yes
IPADDR={{ .IPADDR }}
NETMASK={{ .NETMASK }}
GATEWAY={{ .GATEWAY }}
DNS1=114.114.114.114
DNS2=223.5.5.5
IPV6_PRIVACY=no
`